#!/usr/bin/env python3
"""
NMP Hash Table Generator
========================
Generates hash values for NMP instruction address lookup
Uses the same multiplicative hash algorithm as the hardware

Algorithm: Multiplicative Hash with XOR Mixing
- Combined = RS1_base XOR RS2_base XOR RD_base
- Mixed = Combined * GOLDEN_RATIO
- Hash = Mixed[31:15] (17 bits)
"""

import sys

# Golden ratio constant (same as hardware)
GOLDEN_RATIO = 0x9E3779B9

def generate_hash(rs1_base, rs2_base, rd_base):
    """
    Generate 17-bit hash from three 32-bit base addresses
    
    Args:
        rs1_base: 32-bit base address for RS1 array
        rs2_base: 32-bit base address for RS2 array
        rd_base:  32-bit base address for RD array
        
    Returns:
        17-bit hash value (0 to 131071)
    """
    # Step 1: XOR combine the three addresses
    combined = (rs1_base ^ rs2_base ^ rd_base) & 0xFFFFFFFF
    
    # Step 2: Multiplicative hash with golden ratio
    mixed = (combined * GOLDEN_RATIO) & 0xFFFFFFFF
    
    # Step 3: Extract bits [31:15]
    hash_value = (mixed >> 15) & 0x1FFFF
    
    return hash_value

def create_nmp_instruction(hash_value, array_size, hash_mode=True):
    """
    Create NMP instruction with embedded hash
    
    Format:
        [31:15] - 17-bit hash
        [14]    - hash mode enable (1=hash, 0=legacy)
        [13:12] - funct3[1:0] (00=ADD)
        [11:7]  - array size (5 bits)
        [6:0]   - opcode (0x6b)
    
    Args:
        hash_value: 17-bit hash
        array_size: 5-bit array size
        hash_mode: True for hash mode, False for legacy
        
    Returns:
        32-bit instruction
    """
    opcode = 0x6b  # NMP opcode
    funct3 = 0x00  # ADD operation
    mode_bit = 1 if hash_mode else 0
    
    instruction = (
        ((hash_value & 0x1FFFF) << 15) |
        (mode_bit << 14) |
        ((funct3 & 0x03) << 12) |
        ((array_size & 0x1F) << 7) |
        (opcode & 0x7F)
    )
    
    return instruction

def test_hash_collision_rate(num_tests=10000):
    """
    Test hash collision rate with random addresses
    """
    import random
    
    hashes = set()
    collisions = 0
    
    print(f"\nTesting hash collision rate with {num_tests} random address sets...")
    
    for _ in range(num_tests):
        rs1 = random.randint(0x10000000, 0x90000000) & 0xFFFFFF00
        rs2 = random.randint(0x10000000, 0x90000000) & 0xFFFFFF00
        rd  = random.randint(0x10000000, 0x90000000) & 0xFFFFFF00
        
        h = generate_hash(rs1, rs2, rd)
        
        if h in hashes:
            collisions += 1
        hashes.add(h)
    
    collision_rate = (collisions / num_tests) * 100
    print(f"  Unique hashes: {len(hashes)}")
    print(f"  Collisions: {collisions}")
    print(f"  Collision rate: {collision_rate:.2f}%")
    
    if collision_rate < 1.0:
        print(f"  ✓ PASS: Collision rate < 1%")
    else:
        print(f"  ✗ FAIL: Collision rate >= 1%")

def print_example_hashes():
    """
    Print example hash values for common address patterns
    """
    print("\n" + "="*70)
    print("Example Hash Values")
    print("="*70)
    print(f"{'RS1 Base':>12} {'RS2 Base':>12} {'RD Base':>12} {'Hash':>8} {'Instruction':>12}")
    print("-"*70)
    
    test_cases = [
        (0x10000000, 0x20000000, 0x30000000),
        (0x00001000, 0x00002000, 0x00003000),
        (0x00100000, 0x00200000, 0x00300000),
        (0x12345678, 0x9ABCDEF0, 0x11111111),
        (0xAAAAAAAA, 0x55555555, 0xFFFFFFFF),
    ]
    
    for rs1, rs2, rd in test_cases:
        h = generate_hash(rs1, rs2, rd)
        instr = create_nmp_instruction(h, 8, True)
        print(f"0x{rs1:08X}   0x{rs2:08X}   0x{rd:08X}   0x{h:05X}   0x{instr:08X}")

def generate_systemverilog_init(num_entries=20, output_file=None):
    """
    Generate SystemVerilog initialization code for ALT
    """
    import random
    
    print(f"\nGenerating SystemVerilog ALT initialization...")
    
    lines = []
    lines.append("// ALT Initialization Code")
    lines.append("// Generated by generate_hash_table.py\n")
    lines.append("initial begin")
    lines.append("    // Wait for reset")
    lines.append("    wait(rst_n);")
    lines.append("    repeat(10) @(posedge clk);\n")
    
    hashes_used = set()
    
    for i in range(num_entries):
        # Generate unique addresses
        rs1 = (0x00001000 + i * 0x1000) & 0xFFFFFFFF
        rs2 = (0x00100000 + i * 0x1000) & 0xFFFFFFFF
        rd  = (0x01000000 + i * 0x1000) & 0xFFFFFFFF
        
        h = generate_hash(rs1, rs2, rd)
        
        # Handle collisions by adjusting addresses slightly
        retry_count = 0
        while h in hashes_used and retry_count < 100:
            rs1 = (rs1 + 0x100) & 0xFFFFFFFF
            h = generate_hash(rs1, rs2, rd)
            retry_count += 1
        
        hashes_used.add(h)
        
        lines.append(f"    // Entry {i}: Hash=0x{h:05X}")
        lines.append(f"    alt_write_enable = 1;")
        lines.append(f"    alt_write_hash_index = 17'h{h:05X};")
        lines.append(f"    alt_write_rs1_base = 32'h{rs1:08X};")
        lines.append(f"    alt_write_rs2_base = 32'h{rs2:08X};")
        lines.append(f"    alt_write_rd_base = 32'h{rd:08X};")
        lines.append(f"    @(posedge clk);")
        lines.append(f"    alt_write_enable = 0;")
        lines.append(f"    repeat(2) @(posedge clk);\n")
    
    lines.append("    $display(\"ALT initialization complete\");")
    lines.append("end")
    
    sv_code = "\n".join(lines)
    
    if output_file:
        with open(output_file, 'w') as f:
            f.write(sv_code)
        print(f"  Generated: {output_file}")
    else:
        print("\n" + sv_code)

def main():
    """
    Main function - demonstrates hash generation
    """
    print("="*70)
    print("NMP Hash Table Generator")
    print("Multiplicative Hash with XOR Mixing")
    print("Golden Ratio Constant: 0x{:08X}".format(GOLDEN_RATIO))
    print("="*70)
    
    # Print examples
    print_example_hashes()
    
    # Test collision rate
    test_hash_collision_rate(10000)
    
    # Generate SV init code
    print("\n" + "="*70)
    print("Generate SystemVerilog Initialization?")
    print("="*70)
    print("1. Yes - Generate to file")
    print("2. Yes - Print to console")
    print("3. No - Skip")
    
    try:
        choice = input("\nChoice (1-3): ").strip()
        
        if choice == '1':
            filename = input("Output filename [alt_init.sv]: ").strip()
            if not filename:
                filename = "alt_init.sv"
            generate_systemverilog_init(20, filename)
        elif choice == '2':
            generate_systemverilog_init(20, None)
    except (EOFError, KeyboardInterrupt):
        print("\nSkipped.")
    
    print("\n" + "="*70)
    print("Hash generation complete!")
    print("="*70 + "\n")

if __name__ == "__main__":
    main()
